apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-credentials-pod
  # annotations:
  #   "helm.sh/hook": "pre-install, pre-upgrade"
  #   "helm.sh/hook-delete-policy": before-hook-creation"
  #   "helm.sh/hook-delete-timeout": "10"
data:
  username: {{ .Values.registry.username | b64enc }}
  password: {{ .Values.registry.password | b64enc }}
  server: {{ .Values.registry.server | b64enc }}
  email: {{ .Values.registry.email | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: github-credentials
data:
  username: {{ .Values.github.username | b64enc }}
  password: {{ .Values.github.password | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: wso2-credentials
  # annotations:
  #   "helm.sh/hook": "pre-install, pre-upgrade"
  #   "helm.sh/hook-delete-policy": before-hook-creation"
  #   "helm.sh/hook-delete-timeout": "10"
type: Opaque
data:
  username: {{ .Values.wso2Username | b64enc }}
  password: {{ .Values.wso2Password | b64enc }}
